# Generated by Django 3.2.3 on 2021-05-25 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Bin Name')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('address', models.TextField(verbose_name='Bin Address')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Operation Name')),
            ],
        ),
        migrations.CreateModel(
            name='BinOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_frequency', models.IntegerField(verbose_name='Collection Frequency')),
                ('last_collection', models.DateTimeField(verbose_name='Last Collection')),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.bin', verbose_name='Bin')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.operation', verbose_name='Operation')),
            ],
        ),
        migrations.AddField(
            model_name='bin',
            name='operations',
            field=models.ManyToManyField(through='base.BinOperation', to='base.Operation'),
        ),
    ]
