# Generated by Django 3.2.3 on 2021-05-25 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_bin_address'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='binoperation',
            index=models.Index(fields=['bin'], name='base_binope_bin_id_f8d586_idx'),
        ),
    ]
